version: '3'

services:
  mongodb:
    build: ./mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: planitx
      MONGO_INITDB_DATABASE: planitx
      MONGO_ADMIN_USERNAME: planitx
      MONGO_ADMIN_PASSWORD: planitx
    volumes:
      - mongoData:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    ports:
      - "27017:27017"

  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: planitx
      POSTGRES_USER: planitx
      POSTGRES_DB: planitx
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  app:
    build: ./server
    restart: always
    environment:
      MONGO_URI: mongodb://planitx:planitx@mongodb:27017/?authSource=planitx
      MONGO_INITDB_DATABASE: planitx
      PGUSER: planitx
      PGPASSWORD: planitx
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: planitx
    ports:
      - "3000:3000"
    depends_on:
      postgres:
       condition: service_healthy
volumes:
  pgdata:
  mongoData:
